name: Podman Nginx on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-nginx:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        brew install --cask docker
        open /Applications/Docker.app
        sleep 10
        while ! docker system info > /dev/null 2>&1; do sleep 1; done

    - name: Run Podman in Docker
      run: |
        docker run --privileged --name podman-container -d quay.io/podman/stable:latest sleep infinity
        docker exec podman-container podman pull nginx:latest
        docker exec -d podman-container podman run -d -p 8080:80 nginx:latest

    - name: Test Nginx Container
      run: |
        sleep 10 # Wait for Nginx to start
        curl http://localhost:8080
